{{- if and .Values.turn.enabled .Values.coturn.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aileron.fullname" . }}-coturn
  namespace: {{ .Values.coturn.namespace | quote }}
  labels:
    {{- include "aileron.labels" . | nindent 4 }}
    app.kubernetes.io/component: coturn
automountServiceAccountToken: false
{{- end }}
