{{- if and .Values.turn.enabled .Values.coturn.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.coturn.namespace | quote }}
  labels:
    app.kubernetes.io/part-of: aileron
    app.kubernetes.io/component: coturn
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
{{- end }}
