apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aileron.fullname" . }}-secrets
  labels:
    {{- include "aileron.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.postgres.auth.username | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
  keycloak-admin-user: {{ .Values.keycloak.auth.adminUser | quote }}
  keycloak-admin-password: {{ .Values.keycloak.auth.adminPassword | quote }}
  workspace-manager-secret-key: {{ .Values.workspaceManager.env.SECRET_KEY | quote }}
