{{- if and .Values.workspaceOperator.enabled .Values.workspaceOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aileron.serviceAccountName" (dict "root" . "serviceAccount" .Values.workspaceOperator.serviceAccount "nameSuffix" "workspace-operator") }}
  namespace: {{ include "aileron.workspaceRuntimeNamespace" . | quote }}
  labels:
    {{- include "aileron.labels" . | nindent 4 }}
{{- end }}
