#!/usr/bin/env python3
"""Generate and verify the committed Browser connectivity contract bundle."""

from __future__ import annotations

import argparse
import copy
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPOSITORY_ROOT = ROOT.parents[1]
BUNDLE_OUTPUT = ROOT / "generated" / "contract-bundle.json"
GO_OUTPUT = (
    REPOSITORY_ROOT
    / "workspace-operator/internal/controller/browser_connectivity_contract_generated.go"
)
PYTHON_OUTPUT = (
    REPOSITORY_ROOT
    / "workspace-manager/app/modules/workspace/browser_connectivity_contract_generated.py"
)
SOURCES = (
    "turn-reachability-profile.schema.json",
    "turn-path-evidence.schema.json",
    "browser-connectivity-projection.schema.json",
    "profile-digest-vectors.json",
    "evaluator-cases.json",
    "schema-conformance-vectors.json",
)


def _load(name: str) -> dict:
    return json.loads((ROOT / name).read_text(encoding="utf-8"))


def generate_bundle() -> bytes:
    bundle = {
        "generated": True,
        "message": "DO NOT EDIT; run generate_contract_bundle.py",
        "contracts": {name: _load(name) for name in SOURCES},
    }
    return (
        json.dumps(bundle, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode()


def contract_metadata() -> dict[str, object]:
    projection = _load("browser-connectivity-projection.schema.json")
    evidence = _load("turn-path-evidence.schema.json")
    return {
        "version": projection["properties"]["contractVersion"]["const"],
        "states": projection["properties"]["state"]["enum"],
        "admissions": projection["properties"]["admission"]["enum"],
        "reasons": projection["properties"]["reason"]["enum"],
        "error_codes": projection["properties"]["errorCode"]["enum"],
        "outcomes": evidence["$defs"]["evidence"]["properties"]["outcome"]["enum"],
    }


def generate_go() -> bytes:
    metadata = contract_metadata()
    states = metadata["states"]
    admissions = metadata["admissions"]
    outcomes = metadata["outcomes"]
    constants = [("BrowserConnectivityContractVersion", metadata["version"])]
    lines = [
        "// Code generated by contracts/browser-connectivity/generate_contract_bundle.py. DO NOT EDIT.",
        "package controller",
        "",
        "const (",
    ]
    for value in states:
        name = "".join(part.title() for part in value.split("_"))
        constants.append((f"BrowserConnectivity{name}", value))
    for value in admissions:
        name = "".join(part.title() for part in value.split("_"))
        constants.append((f"BrowserConnectivity{name}", value))
    for value in outcomes:
        name = "".join(part.title() for part in value.split("_"))
        constants.append((f"TURNProbeOutcome{name}", value))
    width = max(len(name) for name, _ in constants)
    lines.extend(f'\t{name.ljust(width)} = "{value}"' for name, value in constants)
    lines.extend((")", ""))
    return "\n".join(lines).encode()


def generate_python() -> bytes:
    metadata = contract_metadata()

    def frozen_set(name: str, values: object) -> str:
        items = "\n".join(f"        {json.dumps(value)}," for value in values)
        return f"{name} = frozenset(\n    [\n{items}\n    ]\n)\n"

    content = (
        "# Generated Browser connectivity contract constants. DO NOT EDIT.\n\n"
        f'BROWSER_CONNECTIVITY_CONTRACT_VERSION = {json.dumps(metadata["version"])}\n'
        + frozen_set("CONNECTIVITY_STATES", metadata["states"])
        + frozen_set("CONNECTIVITY_ADMISSIONS", metadata["admissions"])
        + frozen_set("CONNECTIVITY_REASONS", metadata["reasons"])
        + frozen_set("CONNECTIVITY_ERROR_CODES", metadata["error_codes"])
        + frozen_set("EVIDENCE_OUTCOMES", metadata["outcomes"])
    )
    return content.encode()


def _resolve(schema: dict, root: dict) -> dict:
    if "$ref" in schema:
        current: object = root
        for part in schema["$ref"].removeprefix("#/").split("/"):
            current = current[part]  # type: ignore[index]
        return _resolve(current, root)  # type: ignore[arg-type]
    return schema


def _validate(instance: object, schema: dict, root: dict, path: str = "$") -> None:
    schema = _resolve(schema, root)
    if "const" in schema and instance != schema["const"]:
        raise ValueError(f"{path} does not match const")
    if "enum" in schema and instance not in schema["enum"]:
        raise ValueError(f"{path} is not in enum")
    expected_type = schema.get("type")
    type_matches = {
        "object": isinstance(instance, dict),
        "array": isinstance(instance, list),
        "string": isinstance(instance, str),
        "integer": isinstance(instance, int) and not isinstance(instance, bool),
    }
    if expected_type in type_matches and not type_matches[expected_type]:
        raise ValueError(f"{path} has the wrong type")
    if isinstance(instance, dict):
        required = set(schema.get("required", []))
        missing = required - set(instance)
        if missing:
            raise ValueError(f"{path} is missing {sorted(missing)}")
        properties = schema.get("properties", {})
        if schema.get("additionalProperties") is False:
            unknown = set(instance) - set(properties)
            if unknown:
                raise ValueError(f"{path} has unknown fields {sorted(unknown)}")
        if len(instance) < schema.get("minProperties", 0):
            raise ValueError(f"{path} has too few properties")
        for key, value in instance.items():
            if key in properties:
                _validate(value, properties[key], root, f"{path}.{key}")
            elif isinstance(schema.get("additionalProperties"), dict):
                _validate(value, schema["additionalProperties"], root, f"{path}.{key}")
    elif isinstance(instance, list):
        if len(instance) < schema.get("minItems", 0):
            raise ValueError(f"{path} has too few items")
        for index, value in enumerate(instance):
            _validate(value, schema.get("items", {}), root, f"{path}[{index}]")
    elif isinstance(instance, str):
        if len(instance) < schema.get("minLength", 0) or len(instance) > schema.get(
            "maxLength", len(instance)
        ):
            raise ValueError(f"{path} has an invalid length")
        if "pattern" in schema and re.search(schema["pattern"], instance) is None:
            raise ValueError(f"{path} does not match pattern")
    elif isinstance(instance, int):
        if instance < schema.get("minimum", instance) or instance > schema.get(
            "maximum", instance
        ):
            raise ValueError(f"{path} is outside the allowed range")


def _semantic_schema(schema: dict, root: dict) -> object:
    schema = copy.deepcopy(_resolve(schema, root))
    schema.pop("$schema", None)
    schema.pop("$id", None)
    schema.pop("title", None)
    schema.pop("$defs", None)
    if schema.get("type") == "string" and "enum" in schema:
        schema.pop("type")
    normalized: dict[str, object] = {}
    for key, value in sorted(schema.items()):
        if isinstance(value, dict):
            normalized[key] = _semantic_schema(value, root)
        elif isinstance(value, list):
            items = [
                _semantic_schema(item, root) if isinstance(item, dict) else item
                for item in value
            ]
            normalized[key] = sorted(items) if key in {"enum", "required"} else items
        else:
            normalized[key] = value
    return normalized


def validate_helm_schema() -> None:
    canonical = _load("turn-reachability-profile.schema.json")
    helm = json.loads(
        (REPOSITORY_ROOT / "helm/aileron/values.schema.json").read_text(
            encoding="utf-8"
        )
    )
    profile = helm["definitions"]["turnReachabilityProfile"]
    if _semantic_schema(profile, helm) != _semantic_schema(canonical, canonical):
        raise SystemExit(
            "Helm TURN profile schema is not equivalent to the canonical contract"
        )
    vectors = _load("schema-conformance-vectors.json")
    for vector in vectors["vectors"]:
        for candidate, root in ((canonical, canonical), (profile, helm)):
            accepted = True
            try:
                _validate(vector["profile"], candidate, root)
            except ValueError:
                accepted = False
            if accepted != vector["valid"]:
                raise SystemExit(
                    f"Schema vector {vector['name']} produced {accepted}, expected {vector['valid']}"
                )


def outputs() -> dict[Path, bytes]:
    return {
        BUNDLE_OUTPUT: generate_bundle(),
        GO_OUTPUT: generate_go(),
        PYTHON_OUTPUT: generate_python(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected_outputs = outputs()
    validate_helm_schema()
    if arguments.check:
        for output, expected in expected_outputs.items():
            if not output.exists() or output.read_bytes() != expected:
                raise SystemExit(
                    f"Browser connectivity generated output drifted: {output}"
                )
        return 0
    for output, expected in expected_outputs.items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
