"""Canonical Runtime database connection interface and adapters."""

from .core import (
    AsyncpgRuntimeConnectionAdapter,
    CallbackRuntimeConnectionSink,
    CallbackRuntimeConnectionSource,
    RuntimeConnectionAdapter,
    RuntimeConnectionContractError,
    RuntimeConnectionDriverError,
    RuntimeConnectionRef,
    RuntimeConnectionSink,
    RuntimeConnectionSource,
    RuntimeConnectionTransportError,
    RuntimeDatabaseConnectionError,
    RuntimeDatabaseConnections,
    RuntimeLoginGrant,
    SecretFileRuntimeConnectionSink,
    SecretFileRuntimeConnectionSource,
    SensitivePostgresDsn,
    SQLAlchemyRuntimeConnectionAdapter,
)

__all__ = [
    "AsyncpgRuntimeConnectionAdapter",
    "CallbackRuntimeConnectionSink",
    "CallbackRuntimeConnectionSource",
    "RuntimeConnectionAdapter",
    "RuntimeConnectionContractError",
    "RuntimeConnectionDriverError",
    "RuntimeConnectionRef",
    "RuntimeConnectionSink",
    "RuntimeConnectionSource",
    "RuntimeConnectionTransportError",
    "RuntimeDatabaseConnectionError",
    "RuntimeDatabaseConnections",
    "RuntimeLoginGrant",
    "SQLAlchemyRuntimeConnectionAdapter",
    "SecretFileRuntimeConnectionSink",
    "SecretFileRuntimeConnectionSource",
    "SensitivePostgresDsn",
]
