site:
  siteId: ""
  workspaceId: ""
  hostname: ""
image:
  repository: ""
  digest: ""
imagePullSecretName: ""
tlsSecretName: ""
ingressClassName: ""
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 256Mi
