// Code generated by contracts/browser-connectivity/generate_contract_bundle.py. DO NOT EDIT.
package controller

const (
	BrowserConnectivityContractVersion = "browser-connectivity/v1"
	BrowserConnectivityPending         = "pending"
	BrowserConnectivityReady           = "ready"
	BrowserConnectivityDegraded        = "degraded"
	BrowserConnectivityNotReady        = "not_ready"
	BrowserConnectivityUnavailable     = "unavailable"
	BrowserConnectivityAllowed         = "allowed"
	BrowserConnectivityDenied          = "denied"
	TURNProbeOutcomeSuccess            = "success"
	TURNProbeOutcomeFailure            = "failure"
)
