// Code generated from contracts/controller-dependencies/registry.json. DO NOT EDIT.

package controller

import controllerdependencies "workspace-operator/internal/controllerdependencies"

var canonicalControllerDependencies = []controllerdependencies.Dependency{
	{Identity: "cilium.endpoints", OwnerController: "workspace-controller", APIGroup: "cilium.io", Resource: "ciliumendpoints", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "cilium.io/v2.CiliumEndpoint", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"get", "list", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("ciliumEnabled"), EventMapperIdentity: "ciliumEndpointToWorkspace"},
	{Identity: "cilium.network-policies", OwnerController: "workspace-controller", APIGroup: "cilium.io", Resource: "ciliumnetworkpolicies", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "cilium.io/v2.CiliumNetworkPolicy", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"create", "delete", "get", "list", "update", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("ciliumEnabled"), EventMapperIdentity: "ownerReference"},
	{Identity: "core.persistent-volume-claims", OwnerController: "workspace-controller", APIGroup: "", Resource: "persistentvolumeclaims", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "corev1.PersistentVolumeClaim", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"create", "delete", "get", "list", "update", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always"), EventMapperIdentity: "ownerReference"},
	{Identity: "core.pods", OwnerController: "workspace-controller", APIGroup: "", Resource: "pods", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "corev1.Pod", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"get", "list", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always"), EventMapperIdentity: "managedPodToWorkspace"},
	{Identity: "core.secrets", OwnerController: "workspace-controller", APIGroup: "", Resource: "secrets", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "corev1.Secret", AccessMode: controllerdependencies.AccessMode("cached"), Verbs: []string{"create", "get", "list", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always")},
	{Identity: "core.service-accounts", OwnerController: "workspace-controller", APIGroup: "", Resource: "serviceaccounts", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "corev1.ServiceAccount", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"create", "delete", "get", "list", "update", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always"), EventMapperIdentity: "ownerReference"},
	{Identity: "core.services", OwnerController: "workspace-controller", APIGroup: "", Resource: "services", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "corev1.Service", AccessMode: controllerdependencies.AccessMode("cached"), Verbs: []string{"create", "delete", "get", "list", "update", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always")},
	{Identity: "storage.storage-classes", OwnerController: "workspace-controller", APIGroup: "storage.k8s.io", Resource: "storageclasses", Scope: controllerdependencies.Scope("cluster"), TypedObject: "storagev1.StorageClass", AccessMode: controllerdependencies.AccessMode("directLookup"), Verbs: []string{"get"}, EnabledCondition: controllerdependencies.EnabledCondition("storageClassesConfigured"), ProbeIdentity: "configuredStorageClasses"},
	{Identity: "workloads.deployments", OwnerController: "workspace-controller", APIGroup: "apps", Resource: "deployments", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "appsv1.Deployment", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"create", "delete", "get", "list", "update", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always"), EventMapperIdentity: "ownerReference"},
	{Identity: "workspace.finalizers", OwnerController: "workspace-controller", APIGroup: "platform.aileron.io", Resource: "workspaces/finalizers", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "workspacev1alpha1.Workspace", AccessMode: controllerdependencies.AccessMode("cached"), Verbs: []string{"update"}, EnabledCondition: controllerdependencies.EnabledCondition("always")},
	{Identity: "workspace.primary", OwnerController: "workspace-controller", APIGroup: "platform.aileron.io", Resource: "workspaces", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "workspacev1alpha1.Workspace", AccessMode: controllerdependencies.AccessMode("watched"), Verbs: []string{"get", "list", "update", "watch"}, EnabledCondition: controllerdependencies.EnabledCondition("always"), EventMapperIdentity: "primaryResource"},
	{Identity: "workspace.status", OwnerController: "workspace-controller", APIGroup: "platform.aileron.io", Resource: "workspaces/status", Scope: controllerdependencies.Scope("namespaced"), TypedObject: "workspacev1alpha1.Workspace", AccessMode: controllerdependencies.AccessMode("cached"), Verbs: []string{"update"}, EnabledCondition: controllerdependencies.EnabledCondition("always")},
}
