[supervisord]
nodaemon=true
pidfile=/tmp/aileron-browser/supervisor/supervisord.pid
childlogdir=/tmp/aileron-browser/supervisor
logfile=/dev/null
logfile_maxbytes=0
loglevel=info

[include]
files=/etc/neko/supervisord.kubernetes/*.conf

[program:x-server]
environment=HOME="%(ENV_HOME)s",DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
command=/usr/bin/X %(ENV_DISPLAY)s -config /etc/neko/xorg.kubernetes.conf -noreset -nolisten tcp -logfile /dev/stdout -logverbose 0 -verbose 0
autorestart=true
priority=300
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:pulseaudio]
environment=HOME="%(ENV_HOME)s",DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",PULSE_SERVER="%(ENV_PULSE_SERVER)s"
command=/usr/bin/pulseaudio -n --file=/etc/pulse/default.kubernetes.pa --log-target=stderr --log-level=error --disallow-module-loading --disallow-exit --exit-idle-time=-1
autorestart=true
priority=300
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:neko]
environment=HOME="%(ENV_HOME)s",DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",PULSE_SERVER="%(ENV_PULSE_SERVER)s"
command=/usr/bin/neko serve --config /etc/neko/neko.kubernetes.yaml
stopsignal=INT
stopwaitsecs=3
autorestart=true
priority=800
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[unix_http_server]
file=/tmp/aileron-browser/supervisor/supervisor.sock
chmod=0600

[supervisorctl]
serverurl=unix:///tmp/aileron-browser/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
