[program:chromium]
environment=HOME="%(ENV_HOME)s",DISPLAY="%(ENV_DISPLAY)s",LANG="zh_TW.UTF-8",LC_ALL="zh_TW.UTF-8",LANGUAGE="zh_TW:zh",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
command=/usr/bin/chromium
  --window-position=0,0
  --display=%(ENV_DISPLAY)s
  --user-data-dir=%(ENV_AILERON_BROWSER_PROFILE_DIR)s
  --no-first-run
  --start-maximized
  --bwsi
  --disable-file-system
  --disable-gpu
  --disable-software-rasterizer
  --no-sandbox
  --remote-debugging-port=9222
  --remote-allow-origins=*
  --lang=zh-TW
stopsignal=INT
autorestart=true
priority=800
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openbox]
environment=HOME="%(ENV_HOME)s",DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
command=/usr/bin/openbox --config-file /etc/neko/openbox.xml
autorestart=true
priority=300
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
