[program:cdp-proxy]
command=node /opt/cdp-proxy/cdp-proxy.js
environment=CDP_PORT="9222",CONTAINER_NAME="%(ENV_CONTAINER_NAME)s"
autorestart=true
priority=850
stdout_logfile=/var/log/neko/cdp-proxy.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
redirect_stderr=true
