"""
Message builder functions.

Modeled after agor-main's message-builder.ts
Provides pure functions for creating various types of messages.
"""

from typing import Any, Dict, List, Optional

from app.modules.agent_session.domain.enums import MessageRole, MessageType
from app.modules.agent_session.schemas.message import MessageCreate
from app.modules.agent_session.services.message_service import MessageService
from app.modules.agent_session.services.tools.base.types import TokenUsage


async def create_user_message(
    session_id: str,
    prompt: str,
    task_id: Optional[str],
    index: int,
    message_service: MessageService,
) -> Dict[str, Any]:
    """
    Create user message.

    Args:
        session_id: Session ID
        prompt: User prompt
        task_id: Task ID
        index: Message index
        message_service: Message service

    Returns:
        Created message
    """
    data = MessageCreate(
        session_id=session_id,
        task_id=task_id,
        type=MessageType.USER,
        role=MessageRole.USER,
        content=[{"type": "text", "text": prompt}],
        index=index,
        metadata={},
    )
    
    message = await message_service.create_message(data)

    # Convert content to content_blocks format (format expected by frontend)
    content_blocks = []
    if isinstance(message.content, str):
        content_blocks = [{"type": "text", "text": message.content}]
    elif isinstance(message.content, list):
        content_blocks = message.content

    return {
        "message_id": message.id,
        "session_id": message.session_id,
        "task_id": message.task_id,
        "type": message.type.value if hasattr(message.type, "value") else message.type,
        "role": message.role.value if hasattr(message.role, "value") else message.role,
        "index": message.index,
        "content_blocks": content_blocks,
        "created_at": message.created_at.isoformat() if message.created_at else None,
    }


async def create_assistant_message(
    session_id: str,
    message_id: str,
    content: List[Dict[str, Any]],
    tool_uses: Optional[List[Dict[str, Any]]],
    task_id: Optional[str],
    index: int,
    resolved_model: Optional[str],
    message_service: MessageService,
    parent_tool_use_id: Optional[str] = None,
    token_usage: Optional[TokenUsage] = None,
) -> str:
    """
    Create assistant message.

    Args:
        session_id: Session ID
        message_id: Message ID (unused, generated by MessageService)
        content: Content blocks
        tool_uses: Tool uses
        task_id: Task ID
        index: Message index
        resolved_model: Resolved model name
        message_service: Message service
        parent_tool_use_id: Parent tool use ID
        token_usage: Token usage

    Returns:
        Actual created message ID
    """
    # Create metadata
    metadata: Dict[str, Any] = {
        "source": "claude-sdk",
    }

    if resolved_model:
        metadata["model"] = resolved_model

    if token_usage:
        # Remove None values
        tokens = {
            "input": token_usage.input,
            "output": token_usage.output,
        }
        if token_usage.cache_read is not None:
            tokens["cache_read"] = token_usage.cache_read
        if token_usage.cache_creation is not None:
            tokens["cache_creation"] = token_usage.cache_creation

        metadata["tokens"] = tokens

    if parent_tool_use_id:
        metadata["parent_tool_use_id"] = parent_tool_use_id

    data = MessageCreate(
        session_id=session_id,
        task_id=task_id,
        type=MessageType.ASSISTANT,
        role=MessageRole.ASSISTANT,
        content=content,
        index=index,
        metadata=metadata,
    )

    message = await message_service.create_message(data)
    return message.id


async def create_tool_result_message(
    session_id: str,
    content: List[Dict[str, Any]],
    task_id: Optional[str],
    index: int,
    message_service: MessageService,
) -> str:
    """
    Create tool result message.

    Args:
        session_id: Session ID
        content: Content blocks (containing tool_result)
        task_id: Task ID
        index: Message index
        message_service: Message service

    Returns:
        Actual created message ID
    """
    metadata: Dict[str, Any] = {
        "source": "claude-sdk",
        "is_tool_result": True,
    }

    data = MessageCreate(
        session_id=session_id,
        task_id=task_id,
        type=MessageType.USER,  # Claude SDK uses user role to send tool_result
        role=MessageRole.USER,
        content=content,
        index=index,
        metadata=metadata,
    )

    message = await message_service.create_message(data)
    return message.id


async def create_system_message(
    session_id: str,
    content: List[Dict[str, Any]],
    task_id: Optional[str],
    index: int,
    resolved_model: Optional[str],
    message_service: MessageService,
) -> str:
    """
    Create system message.

    Args:
        session_id: Session ID
        content: Content blocks
        task_id: Task ID
        index: Message index
        resolved_model: Resolved model name
        message_service: Message service

    Returns:
        Actual created message ID
    """
    metadata: Dict[str, Any] = {
        "source": "claude-sdk",
    }

    if resolved_model:
        metadata["model"] = resolved_model

    data = MessageCreate(
        session_id=session_id,
        task_id=task_id,
        type=MessageType.SYSTEM,
        role=MessageRole.SYSTEM,
        content=content,
        index=index,
        metadata=metadata,
    )

    message = await message_service.create_message(data)
    return message.id

